'use server'

import { Resend } from 'resend'
import { getBaseUrl } from '@/lib/utils'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendContactEmail(formData: {
  name: string
  email: string
  subject: string
  message: string
}) {
  const { name, email, subject, message } = formData
  const baseUrl = getBaseUrl()

  if (!name || !email || !subject || !message) {
    return { error: 'All fields are required' }
  }

  try {
    const { data, error } = await resend.emails.send({
      from: 'George Ongoro <george.blog@deepread.website>', 
      to: 'george.blog@deepread.website',
      subject: `Contact Form: ${subject}`,
      replyTo: email,
      text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
      html: `
        <div style="font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace; padding: 40px; background-color: #ffffff; color: #000000;">
          <div style="max-width: 600px; margin: 0 auto; border: 1px solid #eeeeee; padding: 40px;">
            <div style="margin-bottom: 40px; border-bottom: 1px solid #000000; padding-bottom: 20px;">
              <h1 style="margin: 0; font-size: 12px; font-weight: 900; text-transform: uppercase; tracking-widest: 0.2em;">
                CONTACT<span style="color: #ff3e00;">.</span>FORM
              </h1>
            </div>
            
            <div style="margin-bottom: 32px;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #999999; margin-bottom: 8px; letter-spacing: 0.1em;">Sender</div>
              <div style="font-size: 14px; font-weight: 700;">${name} &lt;${email}&gt;</div>
            </div>

            <div style="margin-bottom: 32px;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #999999; margin-bottom: 8px; letter-spacing: 0.1em;">Subject</div>
              <div style="font-size: 14px; font-weight: 700;">${subject}</div>
            </div>

            <div style="margin-top: 40px; padding: 32px; background-color: #f9f9f9; border-left: 4px solid #ff3e00;">
              <div style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #999999; margin-bottom: 16px; letter-spacing: 0.1em;">Message</div>
              <div style="font-size: 15px; line-height: 1.6; white-space: pre-wrap;">${message}</div>
            </div>

            <div style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #eeeeee; text-align: left;">
              <p style="margin: 0; color: #bbbbbb; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;">
                Generated by george.blog // ${new Date().toISOString()}
              </p>
            </div>
          </div>
        </div>
      `,
    })

    if (error) {
      console.error('Resend error:', error)
      return { error: error.message }
    }

    return { success: true, data }
  } catch (err) {
    console.error('Contact email error:', err)
    return { error: 'Failed to send email. Please try again later.' }
  }
}
